package com.sim.traveltool.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sim.traveltool.bean.record.DaKaRecord;

import com.sim.traveltool.greendao.db.DaKaRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daKaRecordDaoConfig;

    private final DaKaRecordDao daKaRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daKaRecordDaoConfig = daoConfigMap.get(DaKaRecordDao.class).clone();
        daKaRecordDaoConfig.initIdentityScope(type);

        daKaRecordDao = new DaKaRecordDao(daKaRecordDaoConfig, this);

        registerDao(DaKaRecord.class, daKaRecordDao);
    }
    
    public void clear() {
        daKaRecordDaoConfig.clearIdentityScope();
    }

    public DaKaRecordDao getDaKaRecordDao() {
        return daKaRecordDao;
    }

}
