package com.sim.sqlitelibrary.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sim.sqlitelibrary.bean.DaKaRecord;
import com.sim.sqlitelibrary.bean.RecordDataBean;

import com.sim.sqlitelibrary.greendao.db.DaKaRecordDao;
import com.sim.sqlitelibrary.greendao.db.RecordDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daKaRecordDaoConfig;
    private final DaoConfig recordDataBeanDaoConfig;

    private final DaKaRecordDao daKaRecordDao;
    private final RecordDataBeanDao recordDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daKaRecordDaoConfig = daoConfigMap.get(DaKaRecordDao.class).clone();
        daKaRecordDaoConfig.initIdentityScope(type);

        recordDataBeanDaoConfig = daoConfigMap.get(RecordDataBeanDao.class).clone();
        recordDataBeanDaoConfig.initIdentityScope(type);

        daKaRecordDao = new DaKaRecordDao(daKaRecordDaoConfig, this);
        recordDataBeanDao = new RecordDataBeanDao(recordDataBeanDaoConfig, this);

        registerDao(DaKaRecord.class, daKaRecordDao);
        registerDao(RecordDataBean.class, recordDataBeanDao);
    }
    
    public void clear() {
        daKaRecordDaoConfig.clearIdentityScope();
        recordDataBeanDaoConfig.clearIdentityScope();
    }

    public DaKaRecordDao getDaKaRecordDao() {
        return daKaRecordDao;
    }

    public RecordDataBeanDao getRecordDataBeanDao() {
        return recordDataBeanDao;
    }

}
